on:
  push:
    tags:
      - v0.*.*
      - v1.*.*

jobs:
  tests:
    name: Continuous Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Checking the code
        run: make tools lint test

      - name: Checking the version
        run: make check-version
